[[subsystems]]
id = "drivetrain"
name = "Drivetrain"
config = "swerve.toml"
enabled = true

[[subsystems]]
id = "elevator_structure"
name = "Elevator Structure"
enabled = false

[[subsystems]]
id = "algae_intake"
name = "Algae Intake"
enabled = false


[[subsystems]]
id = "deep_hang"
name = "Deep Hang"
enabled = false