[[subsystems]]
id = "drivetrain"
name = "Drivetrain"
config = "swerve.toml"
enabled = true

[[subsystems]]
id = "elevator_structure"
name = "Elevator Structure"
enabled = true

[[subsystems]]
id = "arm"
name = "Arm"
config = "arm.toml"

[[subsystems]]
id = "algae_intake"
name = "Algae Intake"
enabled = true