[baseModule]
wheelRadius = 0.04318

[baseModule.io.drive]
motorType = "kBrushless"
idleMode = "kBrake"
stallLimit = 50
gearRatio = 8.14

[baseModule.io.turn]
inverted = true
idleMode = "kBrake"
motorType = "kBrushless"
stallLimit = 20
gearRatio = 21.43

[[modules]]
    name = "Front Left"
    xPos = 3.175
    yPos = 3.175

    [modules.io.drive]
    canid = 1

    [modules.io.turn]
    canid = 2

    [modules.io.cancoder]
    canid = 3
    zeroRotationRad = -3.00

[[modules]]
    name = "Front Right"
    xPos = 3.175
    yPos = -3.175

    [modules.io.drive]
    canid = 4

    [modules.io.turn]
    canid = 5

    [modules.io.cancoder]
    canid = 6
    zeroRotationRad = 0.32

[[modules]]
    name = "Back Left"
    xPos = -3.175
    yPos = 3.175

    [modules.io.drive]
    canid = 7

    [modules.io.turn]
    canid = 8

    [modules.io.cancoder]
    canid = 9
    zeroRotationRad = 2.11

[[modules]]
    name = "Back Right"
    xPos = -3.175
    yPos = -3.175

    [modules.io.drive]
    canid = 10

    [modules.io.turn]
    canid = 11

    [modules.io.cancoder]
    canid = 12
    zeroRotationRad = -1.33